### ISSUE TITLE
[Question] Second replacement task is always failing

### ISSUE THREAD

**Issue by afacanerman** [ThatBlokeCalledJay/set-json-property#2]
Hi,

I have this following pipeline 

![image](https://user-images.githubusercontent.com/972726/57917919-a70ed600-788d-11e9-831a-b741658218e9.png)

first task is always succeeding but second one is failing with 

> Unrecognized escape sequence. 

If I change the order of the tasks to be like 

![image](https://user-images.githubusercontent.com/972726/57918082-f8b76080-788d-11e9-98d1-3b8fb5529dee.png)

again the first one succeeds but the second one fails 

Is this a bug? 
How can I workaround this problem?
Is there any way that I can edit multiple properties with one task? 

thanks

**Comment by afacanerman** [comment]
Sorry it was my bad after the first task ran one of the values had an escape char that was breaking the json syntax.

**Comment by ThatBlokeCalledJay** [comment]
@afacanerman This has actually been addressed and fixed now. You should be able to run your tasks with the escaped characters being handle properly.
