### ISSUE TITLE
Json File Output

### ISSUE THREAD

**Issue by eriksch2709** [ThatBlokeCalledJay/set-json-property#3]
When the output is minified it does not respect escaped characters. I.e. file paths are output as path\path2 rather than the correct output of path\\path2 such that the json files can be read by the application

**Comment by ThatBlokeCalledJay** [comment]
This has been fixed with commit dd7b3dd962534b6e04d1e51c15c00e52bb9c8c49

Thank you for taking the time to create this issue.
