### ISSUE TITLE
Task Does not want to run in hosted MacOS

### ISSUE THREAD

**Issue by scoleman81** [ThatBlokeCalledJay/set-json-property#4]
When building using a hosted MacOS pipeline, I receive an error:
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

**Comment by ThatBlokeCalledJay** [comment]
Hey @scoleman81. This task was indeed only written for the windows environment. In fact the error message suggestion is bang on the button. This is not something I intended to change any time soon, though I imagine a fix would be to port this to Javascript t. Again something I'm not likely to do any time soon. I'm Sorry this task couldn't help solve your problem.
