### ISSUE TITLE
comments in file 

### ISSUE THREAD

**Issue by ahmed3liwa** [ThatBlokeCalledJay/set-json-property#6]
Task fails if i add any comment with // or //// or /**/ ....etc Although it is  just a comment to describe the key or list its expected value.

**Comment by ThatBlokeCalledJay** [comment]
Comments in JSON isnt really an official "thing" it's just nice that in many places, they are supported, I even use comments myself. With that in mind, this app uses an out-of-the-box serializer, which I guess doesn't support comments unfortunately. I'm not going to spend time attempting to circumnavigate this I'm afraid.

**Comment by JohanSpannare** [comment]
+1
